spring:
  profiles:
    active: local
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    cache: false

server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
