spring:
  profiles:
    active: local
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    cache: false

server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false


secret:
  aes256key: /F-JaNdRgUkXp2s5v8y/B?D(G+KbPeSh
  iv: 5u8x/A%D*G-KaPdS

jwt:
  issuer: movie
  secret: p2s5v8y/B?E(H+MbQeThWmZq4t6w9z$C

logging:
  level:
    web: trace